#include <algorithm>
#include <array>
#include <atomic>
#include <chrono>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <mutex>
#include <numeric>
#include <random>
#include <span>
#include <string>
#include <type_traits>
#include <vector>

#include "audio.h"
#include "enhancements.h"
#include "notify.h"
#include "randomizer/merrow_data.h"
#include "zelda_config.h"
#include "zelda_support.h"
#include "json/json.hpp"
#include "librecomp/addresses.hpp"
#include "librecomp/game.hpp"
#include "recomp.h"

// The game's own "set the music volume from the setting" routine,
// generated by N64Recomp; called to re-apply the custom volume live.
extern "C" void func_80026A04(uint8_t* rdram, recomp_context* ctx);
// alCSeqGetLoc and alCSeqSetLoc: the sequence player's save and restore
// of an exact playback position. Dead code in the ROM until now.
extern "C" void func_80038590(uint8_t* rdram, recomp_context* ctx);
extern "C" void func_80038630(uint8_t* rdram, recomp_context* ctx);

namespace data = merrow::data;
using zelda64::audio::CustomMusic;
using zelda64::audio::MusicShuffle;
using zelda64::audio::Options;

namespace {
    Options active;
    bool active_loaded = false;

    std::filesystem::path options_path() {
        return zelda64::get_app_folder_path() / "audio.json";
    }

    // The map music table at 0x80053B00 (ROM 0x054700): 70 six-byte rows of
    // map, submap and track, read by func_8002684C. Merrow's bgmdata lists
    // the track byte of each row plus three code-segment immediates
    // (credits, battle, Mammon) that a ROM write cannot reach here; those
    // are covered by the request hooks instead, so only the table is
    // written.
    constexpr uint32_t bgm_table_start = 0x054700;
    constexpr uint32_t bgm_table_end = 0x0548B0;

    // Tracks. Merrow's map-music pool is 0-26 and 31-41 (27-30 unused), so
    // a roll of 0-37 skips the gap, as Merrow's does; that pool is what any
    // remapped track becomes. The game itself starts tracks beyond it by
    // number - the victory fanfare is 0x2B, the Mammon fight 0x29 - so the
    // ids that can be remapped run further.
    constexpr int track_count = 64;
    constexpr int usable_tracks = 38;
    constexpr int unused_gap_start = 27;
    constexpr int unused_gap_size = 4;

    // Sound effects: the per-effect volume table at 0x80053CAC holds 84
    // entries, of which the first 70 are non-zero; the rest are unused ids.
    constexpr int sfx_count = 70;

    // Per-session tables, built at boot; identity until then.
    std::array<int8_t, track_count> bgm_remap{};
    // Track -> library file name for the tracks custom music replaced.
    std::map<int, std::string> session_songs;

    // The track the main BGM player is on: func_80026658 copies each
    // request here (0x8002673C, a byte; -1 when stopped) right before it
    // loads and starts the sequence, so a change is a start.
    constexpr int32_t bgm_current_track = 0x8008FCC0;
    int last_seen_track = -2;
    std::array<int8_t, sfx_count> sfx_remap{};

    // With the shuffle on, a looping ambience (a waterfall, say) can land on
    // any effect and then never stop, so every effect is cut three seconds
    // after its latest start. The cut is the game's own stop request:
    // func_80025B3C queues { id, volume 0, 0x40 } into the ring buffer the
    // plays go through (eight slots at 0x8005390C / 0x8005392C / 0x8005394C,
    // index at 0x80053970, mirrored to 0x8008FCB0) and the audio thread
    // stops that id. A one-shot is long over by then, so stopping it does
    // nothing; a loop ends.
    constexpr float sfx_cutoff_seconds = 3.0f;
    constexpr int32_t sfx_ring_id = 0x8005390C;
    constexpr int32_t sfx_ring_volume = 0x8005392C;
    constexpr int32_t sfx_ring_param = 0x8005394C;
    constexpr int32_t sfx_ring_index = 0x80053970;
    constexpr int32_t sfx_stop_pending = 0x8008FCB0;
    constexpr int sfx_ring_slots = 8;
    using sfx_clock = std::chrono::steady_clock;
    std::array<sfx_clock::time_point, sfx_count> sfx_started{};
    std::array<bool, sfx_count> sfx_live{};

    void queue_sfx_stop(uint8_t* rdram, int id) {
        int32_t index = static_cast<int32_t>(MEM_W(0, sfx_ring_index)) & (sfx_ring_slots - 1);
        MEM_W(0, sfx_ring_id + index * 4) = id;
        MEM_W(0, sfx_ring_volume + index * 4) = 0;
        MEM_W(0, sfx_ring_param + index * 4) = 0x40;
        index = (index + 1) & (sfx_ring_slots - 1);
        MEM_W(0, sfx_ring_index) = index;
        MEM_W(0, sfx_stop_pending) = index;
    }

    int roll_track(std::mt19937& rng) {
        int track = std::uniform_int_distribution<int>(0, usable_tracks - 1)(rng);
        if (track >= unused_gap_start) {
            track += unused_gap_size;
        }
        return track;
    }

    bool usable_track(int track) {
        return track >= 0 && track < track_count &&
            (track < unused_gap_start || track >= unused_gap_start + unused_gap_size);
    }

    // The music sequence bank: an ALSeqFile at ROM 0xEBABD0 (u16 revision,
    // u16 count, then { u32 offset, u32 len } per sequence, offsets from
    // the bank's own start). func_80025040 DMAs the table into RAM at init
    // and alSeqFileNew turns the offsets into ROM addresses; each play
    // then DMAs the sequence (func_800252D8) into the player's 0x8000-byte
    // buffer (func_8002513C), so that is the size limit. The ROM's tail
    // from 0xF94348 is 0xFF padding, which is where replacements go.
    constexpr uint32_t seq_bank_start = 0xEBABD0;
    constexpr uint32_t rom_free_start = 0xF94348;
    constexpr uint32_t seq_header_size = 17 * 4;

    // ---- the sequence player's buffer
    //
    // The game gives each of its two sequence players a 0x8000-byte buffer
    // out of the audio heap (func_8002513C; the heap is 0x68000 bytes at
    // 0x80331AB0, alHeapInit at 0x80024704) and func_800252D8 DMAs a whole
    // sequence into it every time a track starts, so 32 KB was the limit on
    // a custom file. The game's own 44 sequences are all under 20 KB, but
    // converted music routinely is not.
    //
    // The two buffers are moved instead of grown: the game's RAM reaches
    // 0x804FBC80 and the audio heap is boxed in, while the recomp's RDRAM is
    // 512 MB, so `quest64_audio_seq_buffer_0/1` replace the pointer at the
    // store that keeps it with one from librecomp's own heap (above
    // 0x81000000). Nothing else reads those pointers, the sequence player
    // only ever touches the buffer through the CPU, and the DMA
    // (recomp::do_rom_read) indexes RDRAM without a size check.
    constexpr uint32_t seq_buffer_size = 1024 * 1024;
    int32_t seq_buffers[2] = { 0, 0 };

    // librecomp's heap is set up after the on_init callback but long before
    // the game reaches its audio init, so this allocates on first use rather
    // than at boot.
    int32_t sequence_buffer(uint8_t* rdram, int player) {
        if (seq_buffers[player] == 0) {
            void* mem = recomp::alloc(rdram, seq_buffer_size);
            if (mem == nullptr) {
                return 0;   // leave the game its own buffer
            }
            uint32_t offset = static_cast<uint32_t>(reinterpret_cast<uint8_t*>(mem) - rdram);
            seq_buffers[player] = static_cast<int32_t>(offset + 0x80000000u);
        }
        return seq_buffers[player];
    }

    uint32_t read_u32(const std::vector<uint8_t>& v, size_t at) {
        return (static_cast<uint32_t>(v[at]) << 24) | (static_cast<uint32_t>(v[at + 1]) << 16) |
            (static_cast<uint32_t>(v[at + 2]) << 8) | v[at + 3];
    }

    void write_u32(std::vector<uint8_t>& v, size_t at, uint32_t value) {
        v[at + 0] = static_cast<uint8_t>(value >> 24);
        v[at + 1] = static_cast<uint8_t>(value >> 16);
        v[at + 2] = static_cast<uint8_t>(value >> 8);
        v[at + 3] = static_cast<uint8_t>(value);
    }

    // ---- the library in the ROM, and live changes
    //
    // At boot every file in the folder is appended to the ROM copy (the
    // free tail first, then the ROM grows; a slack of a few MB is added so
    // files dropped in later can be placed while the game runs - the DMA
    // reader indexes the buffer with no size check, and a fixed-size buffer
    // is safe to write into from another thread). Which file a track plays
    // is then only the sequence bank's entry for it: at boot in the ROM
    // copy, and later in the RAM copy of the table that func_80025040 made
    // (pointer at 0x800538F0, entries { ROM address, length } after
    // alSeqFileNew), read by func_800252D8 every time a track starts. So
    // the menu's choices apply to the next play with an 8-byte write,
    // done on the game thread in on_frame.
    constexpr int32_t seq_table_pointer = 0x800538F0;
    constexpr size_t rom_slack = 4 * 1024 * 1024;
    constexpr int32_t bgm_request_track = 0x8008FCC1;
    constexpr int32_t bgm_request_flags = 0x8008FCC2;

    struct Placed {
        uint32_t rom;   // position in the ROM copy
        uint32_t len;
    };
    std::map<std::string, Placed> placed;
    std::array<Placed, zelda64::audio::game_track_count> original_entry{};
    uint32_t rom_cursor = 0;
    size_t rom_capacity = 0;
    bool library_in_rom = false;
    std::ofstream live_log;

    std::mutex live_mutex;
    std::map<int, std::string> pending_entries;   // track -> name, "" for the game's own
    bool pending_all = false;
    int pending_preview = -2;                     // -2 nothing, -1 stop, else a track
    int preview_return = -2;                      // the track to go back to, -2 none
    // A preview's request is watched: if the player is still stopped with
    // nothing pending a while after it, the request is made again (rapid
    // previews can hit a window in the game's own start-up sequence -
    // func_80026658's stop / wait / start steps - where the start is
    // skipped and the request flag is consumed all the same).
    constexpr int32_t seq_player_state = 0x8008F978 + 0x48;   // player 0's ALCSPlayer.state (alSeqpGetState)
    constexpr int32_t bgm_request_timer = 0x8008FCC4;
    int watch_track = -1;
    int watch_frames = 0;
    int watch_retries = 0;

    // The custom music volume, live: the menu's value, and a flag to
    // re-apply it through the game's own routine (func_80026A04 reads the
    // volume setting and calls func_80026554, where the hook scales it).
    std::atomic<int> custom_volume_live{ -1 };
    std::atomic<bool> custom_volume_dirty{ false };

    // "Now playing" is held back a second so it is not spent on the black
    // screen of an area load.
    constexpr int song_notice_delay = 60;
    int song_notice_track = -1;
    int song_notice_countdown = 0;

    // ---- how loud a sequence is
    //
    // Converted music arrives at whatever level its MIDI or its pack was
    // written at, so one file can be twice as loud as the next and the one
    // Custom volume slider - a flat percentage - cannot help: turning the
    // loud one down turns the quiet one down with it. Each file is measured
    // instead, and played at a gain that brings it to the level of the
    // game's own music.
    //
    // The measure is the same walk q64music validates a file with (16 track
    // offsets, then VLQ delta + event, 0xFE a back-reference and 0xFE 0xFE a
    // literal), with the back-references followed - every one of the game's
    // own sequences is compressed with them - accumulating each note's energy - velocity squared, scaled
    // by the channel volume, times how long the note is held - and dividing
    // by the length of the longest track. Power rather than amplitude
    // because the parts are unrelated and add as power does, and an average
    // over time rather than a peak because what is being matched is how loud
    // a song sounds over a minute of play, not its loudest chord. A track
    // that fails to parse contributes nothing; a file where none parse
    // measures 0 and is left at a gain of 1.
    float sequence_level(const uint8_t* f, size_t size) {
        if (size < seq_header_size) {
            return 0.0f;
        }
        auto u32 = [&](size_t at) {
            return (static_cast<uint32_t>(f[at]) << 24) | (static_cast<uint32_t>(f[at + 1]) << 16) |
                (static_cast<uint32_t>(f[at + 2]) << 8) | f[at + 3];
        };
        double energy = 0.0;
        double span = 0.0;
        for (int t = 0; t < 16; t++) {
            uint32_t p = u32(static_cast<size_t>(t) * 4);
            if (p == 0 || p >= size) {
                continue;
            }
            bool bad = false;
            uint32_t copy_left = 0;   // bytes still to take from a back-reference
            uint32_t resume = 0;      // where the stream goes on after it
            auto get = [&]() -> int {
                for (;;) {
                    if (copy_left > 0) {
                        // Inside a referenced block the bytes are taken as
                        // they are: the game's reader does not look for a
                        // further reference in one, and neither does this.
                        if (p >= size) { bad = true; return 0; }
                        uint8_t b = f[p++];
                        if (--copy_left == 0) p = resume;
                        return b;
                    }
                    if (bad || p >= size) { bad = true; return 0; }
                    uint8_t b = f[p++];
                    if (b != 0xFE) return b;
                    if (p < size && f[p] == 0xFE) { p++; return 0xFE; }
                    // FE hi lo len: len bytes from `back` before the FE byte
                    // itself, which is where every one of the game's own 44
                    // sequences is compressed.
                    if (p + 3 > size) { bad = true; return 0; }
                    uint32_t fe = p - 1;
                    uint32_t back = (static_cast<uint32_t>(f[p]) << 8) | f[p + 1];
                    uint32_t len = f[p + 2];
                    p += 3;
                    if (back == 0 || back > fe || len == 0) { bad = true; return 0; }
                    resume = p;
                    p = fe - back;
                    copy_left = len;
                }
            };
            auto vlq = [&]() {
                uint32_t v = 0;
                for (int i = 0; i < 5; i++) {
                    int b = get();
                    v = (v << 7) | (b & 0x7F);
                    if (!(b & 0x80)) break;
                }
                return v;
            };
            int status = 0;
            int volume = 127;
            double ticks = 0.0;
            double track_energy = 0.0;
            bool ended = false;
            while (!bad) {
                ticks += vlq();
                int b = get();
                if (bad) break;
                if (b == 0xFF) {
                    int type = get();
                    status = 0;
                    if (type == 0x2F) { ended = true; break; }
                    if (type == 0x51) { get(); get(); get(); continue; }
                    if (type == 0x2E) { get(); get(); continue; }
                    if (type == 0x2D) { for (int i = 0; i < 6; i++) get(); continue; }
                    bad = true;
                    break;
                }
                if (b & 0x80) { status = b; b = get(); }
                switch (status & 0xF0) {
                case 0x90: {
                    int velocity = get();
                    double duration = vlq();
                    double amplitude = velocity * (volume / 127.0);
                    track_energy += amplitude * amplitude * duration;
                    break;
                }
                case 0xB0: {
                    int value = get();
                    if (b == 7) volume = std::clamp(value, 0, 127);
                    break;
                }
                case 0xC0: break;
                case 0xE0: get(); break;
                default: bad = true; break;
                }
            }
            if (ended && !bad) {
                energy += track_energy;
                span = std::max(span, ticks);
            }
        }
        if (span <= 0.0) {
            return 0.0f;
        }
        return static_cast<float>(std::sqrt(energy / span));
    }

    // Library file name -> its level, and the level custom music is brought
    // to: the median of the game's own 44 sequences, measured the same way.
    // The median rather than the mean so one unusually dense or sparse piece
    // of the game's music cannot drag the target with it.
    std::map<std::string, float> song_level;
    float game_level = 0.0f;

    // What to multiply a custom track's volume by. Clamped, because the
    // measure is an estimate: a song whose parts are all long held pads
    // measures low without sounding quiet, and no reading should be able to
    // silence a track or blow one out.
    float custom_gain(const std::string& name) {
        if (game_level <= 0.0f) {
            return 1.0f;
        }
        auto it = song_level.find(name);
        if (it == song_level.end() || it->second <= 0.0f) {
            return 1.0f;
        }
        return std::clamp(game_level / it->second, 0.35f, 2.5f);
    }

    // Loads a file's bytes into the ROM copy at the cursor. `rom` is the
    // buffer to write (the boot copy, or the live buffer).
    bool place_file(uint8_t* rom, size_t capacity, const std::string& name, std::ostream& log) {
        if (placed.count(name)) {
            return placed[name].len != 0;
        }
        std::ifstream in(zelda64::audio::library_path(name), std::ios::binary);
        std::vector<uint8_t> seq((std::istreambuf_iterator<char>(in)), std::istreambuf_iterator<char>());
        if (seq.size() < seq_header_size + 2 || seq.size() > seq_buffer_size) {
            log << "  " << name << ".seq: skipped, " << seq.size() << " bytes (a sequence is between "
                << (seq_header_size + 2) << " and " << seq_buffer_size << ")\n";
            placed[name] = { 0, 0 };
            return false;
        }
        for (int t = 0; t < 16; t++) {
            uint32_t offset = read_u32(seq, t * 4);
            if (offset != 0 && (offset < seq_header_size || offset >= seq.size())) {
                log << "  " << name << ".seq: skipped, a track offset points outside the file\n";
                placed[name] = { 0, 0 };
                return false;
            }
        }
        uint32_t padded = (static_cast<uint32_t>(seq.size()) + 15) & ~static_cast<uint32_t>(15);
        if (rom_cursor + padded > capacity) {
            log << "  " << name << ".seq: no room left in the ROM; relaunch to make room\n";
            return false;
        }
        std::copy(seq.begin(), seq.end(), rom + rom_cursor);
        placed[name] = { rom_cursor, static_cast<uint32_t>(seq.size()) };
        song_level[name] = sequence_level(seq.data(), seq.size());
        log << "  " << name << ".seq: " << seq.size() << " bytes at ROM 0x" << std::hex << rom_cursor << std::dec
            << ", level " << std::fixed << std::setprecision(1) << song_level[name]
            << " (plays at " << static_cast<int>(custom_gain(name) * 100.0f + 0.5f) << "%)\n"
            << std::defaultfloat;
        rom_cursor += padded;
        return true;
    }

    // Which library file each track gets: the menu's choices (a name that
    // is not in the folder is reported and left as the game's own).
    std::map<int, std::string> plan_custom_music(const Options& options, std::ostream& log) {
        std::map<int, std::string> plan;
        if (options.custom_music != CustomMusic::Custom) {
            return plan;
        }
        for (const auto& [track, name] : options.custom_tracks) {
            if (track < 0 || track >= zelda64::audio::game_track_count || name.empty()) {
                continue;
            }
            if (zelda64::audio::game_track_of(name) >= 0) {
                plan[track] = name;
                continue;
            }
            auto it = placed.find(name);
            if (it == placed.end()) {
                log << "  track " << track << " (" << zelda64::audio::track_label(track) << "): \"" << name
                    << ".seq\" is not in the folder, left as the game's own\n";
                continue;
            }
            if (it->second.len != 0) {
                plan[track] = name;
            }
        }
        return plan;
    }

    // Boot: the whole library into the ROM copy, the chosen entries set.
    void apply_custom_music(std::vector<uint8_t>& patched, const Options& options) {
        std::filesystem::path folder = zelda64::audio::library_folder();
        live_log.open(zelda64::get_app_folder_path() / "custom_music.txt");
        std::ostream& log = live_log;
        log << "Custom music folder: " << folder.string() << "\n";
        std::vector<std::string> library = zelda64::audio::library_files();
        log << "  " << library.size() << " file(s) in the library\n";
        std::vector<std::string> fanfares = zelda64::audio::fanfare_files();
        log << "  " << fanfares.size() << " file(s) in the fanfares folder\n";
        library.insert(library.end(), fanfares.begin(), fanfares.end());

        uint32_t count = (static_cast<uint32_t>(patched[seq_bank_start + 2]) << 8) | patched[seq_bank_start + 3];
        for (int track = 0; track < zelda64::audio::game_track_count && static_cast<uint32_t>(track) < count; track++) {
            uint32_t entry = seq_bank_start + 4 + static_cast<uint32_t>(track) * 8;
            original_entry[track] = { read_u32(patched, entry), read_u32(patched, entry + 4) };
        }

        // The target level, before any file is measured against it. Entries
        // hold offsets from the bank's own start, which is where the
        // sequences sit in the ROM copy being patched.
        std::vector<float> own_levels;
        for (int track = 0; track < zelda64::audio::game_track_count; track++) {
            const Placed& e = original_entry[track];
            size_t at = seq_bank_start + e.rom;
            if (e.len == 0 || at + e.len > patched.size()) {
                continue;
            }
            float level = sequence_level(patched.data() + at, e.len);
            if (level > 0.0f) {
                own_levels.push_back(level);
            }
        }
        if (!own_levels.empty()) {
            std::sort(own_levels.begin(), own_levels.end());
            game_level = own_levels[own_levels.size() / 2];
        }
        log << "  the game's own music measures " << std::fixed << std::setprecision(1) << game_level
            << " over " << own_levels.size() << " sequence(s); custom files are matched to it\n"
            << std::defaultfloat;

        // Room for every file plus slack, in whole MB past the free tail.
        size_t need = 0;
        std::error_code ec;
        for (const std::string& name : library) {
            need += (static_cast<size_t>(std::filesystem::file_size(zelda64::audio::library_path(name), ec)) + 15) & ~static_cast<size_t>(15);
        }
        rom_cursor = rom_free_start;
        size_t wanted = rom_free_start + need + rom_slack;
        if (wanted > patched.size()) {
            patched.resize(((wanted + 0xFFFFF) / 0x100000) * 0x100000, 0xFF);
            log << "  ROM grown to " << patched.size() << " bytes\n";
        }
        rom_capacity = patched.size();
        for (const std::string& name : library) {
            place_file(patched.data(), rom_capacity, name, log);
        }
        library_in_rom = true;

        std::map<int, std::string> plan = plan_custom_music(options, log);
        session_songs.clear();
        for (const auto& [track, name] : plan) {
            uint32_t entry = seq_bank_start + 4 + static_cast<uint32_t>(track) * 8;
            int own = zelda64::audio::game_track_of(name);
            Placed source = own >= 0 ? original_entry[own] : Placed{ placed[name].rom - seq_bank_start, placed[name].len };
            write_u32(patched, entry, source.rom);
            write_u32(patched, entry + 4, source.len);
            log << "  track " << track << " (" << zelda64::audio::track_label(track) << ") <- " << name << "\n";
            session_songs[track] = name;
        }
        if (plan.empty()) {
            log << "  nothing replaced at boot\n";
        }
        log.flush();
    }

    // Game thread: the RAM table entry for one track.
    void write_live_entry(uint8_t* rdram, int track, const std::string& name) {
        int32_t table = static_cast<int32_t>(MEM_W(0, seq_table_pointer));
        if (table == 0 || track < 0 || track >= zelda64::audio::game_track_count) {
            return;
        }
        // The table holds ROM addresses: alSeqFileNew added the bank's
        // address (0xEBABD0, the constant the boot code hands
        // func_8002513C) to each file offset. Not derived from an entry:
        // any entry, entry 0 included, may already point at a custom file.
        uint32_t base = seq_bank_start;
        Placed target = original_entry[track];
        int own = zelda64::audio::game_track_of(name);
        if (own >= 0) {
            target = original_entry[own];
        }
        else if (!name.empty()) {
            std::span<const uint8_t> rom = recomp::get_rom();
            if (!place_file(const_cast<uint8_t*>(rom.data()), rom.size(), name, live_log)) {
                live_log.flush();
                return;
            }
            target = placed[name];
            target.rom -= seq_bank_start;
        }
        MEM_W(0, table + 4 + track * 8) = base + target.rom;
        MEM_W(0, table + 8 + track * 8) = target.len;
        if (name.empty()) {
            session_songs.erase(track);
        }
        else {
            session_songs[track] = name;
        }
        live_log << "  live: track " << track << " (" << zelda64::audio::track_label(track) << ") <- "
                 << (name.empty() ? "the game's own" : name) << "\n";
        live_log.flush();
    }

    // Game thread: UpdateBGM's own writes (0x800267B8): the request byte
    // and the pending bit, consumed by func_80026658 next frame. The game
    // ignores a request for the track already requested, so a restart of
    // the same track goes through a stop first.
    void request_track(uint8_t* rdram, int track) {
        MEM_B(0, bgm_request_track) = static_cast<int8_t>(track);
        MEM_H(0, bgm_request_flags) = static_cast<int16_t>(MEM_HU(0, bgm_request_flags) | 1);
    }
    // The 44 sequences: who plays each (map music table rows at ROM
    // 0x054700 for the areas; the by-number callers for the events: boss
    // pick 0x8001CA28 gives 0 or 0x29 for Mammon, battle 0xD, title 0x1B,
    // death 0x1E, credits 0x14, victory 0x2B on the jingle player). The
    // unnamed ones loop but no table row or immediate reaches them.
    const char* const track_labels[zelda64::audio::game_track_count] = {
        "Boss battle",                                  // 0
        "Baragoon Tunnel",                              // 1
        "Melrode",                                      // 2
        "Dondoran Castle",                              // 3
        "Track 4",                                      // 4
        "Shamwood",                                     // 5
        "Hidden rooms and shrines",                     // 6
        "Buildings (shops, inns, houses)",              // 7
        "Limelin Castle",                               // 8
        "Blue Cave (inner)",                            // 9
        "Cull Hazard",                                  // 10
        "Blue Cave (deep)",                             // 11
        "Forests (inner paths)",                        // 12
        "Battle",                                       // 13
        "Nepty's arena",                                // 14
        "Melrode Monastery",                            // 15
        "Track 16",                                     // 16
        "Track 17",                                     // 17
        "Boil Hole",                                    // 18
        "Save menu",                                    // 19
        "Credits",                                      // 20
        "Fields (Holy Plains, Dondoran Flats, West Carmagh, West Limelin)",   // 21
        "Dindom Dries",                                 // 22
        "Blue Cave",                                    // 23
        "Forests (Connor, Glencoe, Windward)",          // 24
        "Dondoran",                                     // 25
        "Isle of Skye",                                 // 26
        "Title screen",                                 // 27
        "Jingle 28",                                    // 28
        "Jingle 29",                                    // 29
        "Death",                                        // 30
        "Brannoch Castle",                              // 31
        "Track 32",                                     // 32
        "Churches, halls and Mammon's World",           // 33
        "Larapool",                                     // 34
        "Connor Forest",                                // 35
        "Limelin",                                      // 36
        "Normoon",                                      // 37
        "Mammon's World (inner)",                       // 38
        "Brannoch and Baragoon Moor",                   // 39
        "Track 40",                                     // 40
        "Mammon battle",                                // 41
        "Track 42",                                     // 42
        "Victory fanfare",                              // 43
    };

    const int track_menu_order_list[zelda64::audio::game_track_count] = {
        27, 13, 0, 41, 43, 30, 20,
        15, 2, 33, 7, 21, 25, 3, 35, 24, 12, 34, 23, 9, 11, 10, 37, 36, 8, 22, 18, 1, 39, 31, 26, 14, 5, 6, 38,
        4, 16, 17, 19, 28, 29, 32, 40, 42,
    };
}

const char* zelda64::audio::track_label(int track) {
    return track >= 0 && track < game_track_count ? track_labels[track] : "";
}

bool zelda64::audio::track_is_jingle(int track) {
    return track == 28 || track == 29 || track == 30 || track == 43;
}

const int* zelda64::audio::track_menu_order() {
    return track_menu_order_list;
}

std::filesystem::path zelda64::audio::library_folder() {
    return std::filesystem::absolute(zelda64::get_program_path() / "custom_music");
}

std::filesystem::path zelda64::audio::fanfare_folder() {
    return std::filesystem::absolute(zelda64::get_program_path() / "fanfares");
}

// Names are UTF-8 (path::u8string): the menu shows them, the settings
// file stores them (a non-UTF-8 string makes the JSON writer throw), and
// library_path turns one back into a path. A fanfare's name carries the
// "fanfares/" prefix, which names the folder.
std::filesystem::path zelda64::audio::library_path(const std::string& name) {
    if (name.compare(0, fanfare_prefix.size(), fanfare_prefix) == 0) {
        return fanfare_folder() / std::filesystem::u8path(name.substr(fanfare_prefix.size()) + ".seq");
    }
    return library_folder() / std::filesystem::u8path(name + ".seq");
}

namespace {
    std::vector<std::string> seq_files_in(const std::filesystem::path& folder, const std::string& prefix, int* too_big) {
        std::vector<std::string> names;
        int big = 0;
        std::error_code ec;
        for (const auto& entry : std::filesystem::directory_iterator(folder, ec)) {
            if (entry.is_regular_file() && entry.path().extension() == ".seq") {
                // A file the game's sequence buffer cannot hold is never
                // offered; the converter says so when it writes one.
                if (entry.file_size(ec) > seq_buffer_size) {
                    big++;
                    continue;
                }
                std::u8string u8 = entry.path().stem().u8string();
                names.push_back(prefix + std::string(u8.begin(), u8.end()));
            }
        }
        std::sort(names.begin(), names.end());
        if (too_big != nullptr) {
            *too_big = big;
        }
        return names;
    }
}

std::vector<std::string> zelda64::audio::library_files(int* too_big) {
    return seq_files_in(library_folder(), "", too_big);
}

std::vector<std::string> zelda64::audio::fanfare_files(int* too_big) {
    return seq_files_in(fanfare_folder(), fanfare_prefix, too_big);
}

bool zelda64::audio::track_is_fanfare(int track) {
    return track_is_jingle(track);
}

namespace {
}

Options zelda64::audio::load_options() {
    Options o;
    std::ifstream in(options_path());
    if (!in.good()) {
        return o;
    }
    nlohmann::json j;
    try {
        in >> j;
    }
    catch (nlohmann::json::parse_error&) {
        return o;
    }
    auto get = [&j](const char* key, auto& out) {
        auto it = j.find(key);
        if (it != j.end()) {
            try {
                out = it->get<std::remove_reference_t<decltype(out)>>();
            }
            catch (nlohmann::json::type_error&) {}
        }
    };
    // The first version stored music_shuffle as a bool meaning Towns.
    auto music = j.find("music_shuffle");
    if (music != j.end()) {
        if (music->is_boolean()) {
            o.music_shuffle = music->get<bool>() ? MusicShuffle::Towns : MusicShuffle::Off;
        }
        else if (music->is_number_integer()) {
            o.music_shuffle = static_cast<MusicShuffle>(std::clamp(music->get<int>(), 0, 2));
        }
    }
    get("sfx_shuffle", o.sfx_shuffle);
    get("custom_volume", o.custom_volume);
    get("battle_music", o.battle_music);
    o.custom_volume = std::clamp(o.custom_volume, 10, 100);
    // custom_music was a bool for one build (track_NN.seq files) and had a
    // per-launch shuffle (1) for another; anything but off is Custom now.
    auto custom = j.find("custom_music");
    if (custom != j.end()) {
        if (custom->is_boolean()) {
            o.custom_music = custom->get<bool>() ? CustomMusic::Custom : CustomMusic::Off;
        }
        else if (custom->is_number_integer()) {
            o.custom_music = custom->get<int>() != 0 ? CustomMusic::Custom : CustomMusic::Off;
        }
    }
    // The menu offers Custom in place of the track shuffle, not on top.
    if (o.custom_music == CustomMusic::Custom) {
        o.music_shuffle = MusicShuffle::Off;
    }
    auto tracks = j.find("custom_tracks");
    if (tracks != j.end() && tracks->is_object()) {
        for (const auto& [key, value] : tracks->items()) {
            try {
                int track = std::stoi(key);
                if (value.is_string() && track >= 0 && track < zelda64::audio::game_track_count) {
                    o.custom_tracks[track] = value.get<std::string>();
                }
            }
            catch (std::exception&) {}
        }
    }
    return o;
}

void zelda64::audio::save_options(const Options& o) {
    nlohmann::json j;
    j["music_shuffle"] = static_cast<int>(o.music_shuffle);
    j["sfx_shuffle"] = o.sfx_shuffle;
    j["custom_volume"] = o.custom_volume;
    j["battle_music"] = o.battle_music;
    j["custom_music"] = o.custom_music == CustomMusic::Custom ? 2 : 0;
    nlohmann::json tracks = nlohmann::json::object();
    for (const auto& [track, name] : o.custom_tracks) {
        if (!name.empty()) {
            tracks[std::to_string(track)] = name;
        }
    }
    j["custom_tracks"] = tracks;
    std::ofstream out(options_path());
    out << j.dump(4);
}

const Options& zelda64::audio::active_options() {
    if (!active_loaded) {
        active = load_options();
        active_loaded = true;
    }
    return active;
}

namespace { void reset_resume_state(); }

void zelda64::audio::apply_at_boot(uint8_t* rdram) {
    const Options& options = active_options();
    // A relaunch re-initialises librecomp's heap, so last launch's blocks
    // are gone; the hook allocates fresh ones.
    seq_buffers[0] = 0;
    seq_buffers[1] = 0;
    reset_resume_state();
    std::iota(bgm_remap.begin(), bgm_remap.end(), 0);
    std::iota(sfx_remap.begin(), sfx_remap.end(), 0);
    // The library is placed whenever the folder has files, so the menu can
    // switch tracks to it live in any mode.
    bool custom_music = !library_files().empty() || !fanfare_files().empty();
    if (options.music_shuffle == MusicShuffle::Off && !options.sfx_shuffle && !custom_music) {
        return;
    }

    std::mt19937 rng{ std::random_device{}() };

    if (options.music_shuffle != MusicShuffle::Off || custom_music) {
        // Reads back whatever the earlier boot patches left, so this stacks
        // on top of them rather than replacing them. The table is in the
        // boot segment (ROM 0x1000.., 1MB), which has already been copied to
        // RAM at 0x80000400 by now, so each byte goes to both: the ROM copy
        // alone is never read again. The sequence bank, by contrast, is
        // DMA'd from the ROM at init, so its entries need the ROM copy only.
        constexpr uint32_t boot_rom_start = 0x1000;
        constexpr int32_t boot_ram_start = 0x80000400;
        std::span<const uint8_t> rom = recomp::get_rom();
        std::vector<uint8_t> patched(rom.begin(), rom.end());
        if (custom_music) {
            apply_custom_music(patched, options);
        }
        for (size_t i = 0; options.music_shuffle != MusicShuffle::Off && i * 2 + 1 < data::bgmdata.size(); i++) {
            uint32_t address = static_cast<uint32_t>(std::stoul(data::bgmdata[i * 2], nullptr, 16));
            if (address >= bgm_table_start && address < bgm_table_end && address < patched.size()) {
                uint8_t track = static_cast<uint8_t>(roll_track(rng));
                patched[address] = track;
                MEM_B(0, boot_ram_start + static_cast<int32_t>(address - boot_rom_start)) = static_cast<int8_t>(track);
            }
        }
        recomp::set_rom_contents(std::move(patched));
    }

    if (options.music_shuffle == MusicShuffle::All) {
        for (int track = 0; track < track_count; track++) {
            if (usable_track(track)) {
                bgm_remap[track] = static_cast<int8_t>(roll_track(rng));
            }
        }
    }

    if (options.sfx_shuffle) {
        std::shuffle(sfx_remap.begin(), sfx_remap.end(), rng);
    }
}

// UpdateBGM (0x800267B8) and func_800267F8: a0 is the track to start, or
// -1 to stop. Only the tracks the game starts by number come through here;
// the map table's rows are read by func_8002684C and were rewritten above.
extern "C" void quest64_audio_bgm(uint8_t*, recomp_context* ctx) {
    if (zelda64::audio::active_options().music_shuffle != MusicShuffle::All) {
        return;
    }
    int track = static_cast<int8_t>(ctx->r4 & 0xFF);
    if (usable_track(track)) {
        ctx->r4 = S32(bgm_remap[track]);
    }
}

// func_8002513C, at the two stores that keep the sequence buffers the audio
// heap just handed out (0x80025188 for player 0, 0x800251B8 for player 1):
// v0 is that pointer, and is replaced with one of ours. The game's own
// allocations are left to happen and go unused - 64 KB of an audio heap that
// has the room, and not worth a second hook to reclaim.
extern "C" void quest64_audio_seq_buffer_0(uint8_t* rdram, recomp_context* ctx) {
    int32_t buffer = sequence_buffer(rdram, 0);
    if (buffer != 0) {
        ctx->r2 = S32(buffer);
    }
}

extern "C" void quest64_audio_seq_buffer_1(uint8_t* rdram, recomp_context* ctx) {
    int32_t buffer = sequence_buffer(rdram, 1);
    if (buffer != 0) {
        ctx->r2 = S32(buffer);
    }
}

// The track a random encounter starts. Boss music comes from the table at
// 0x8001CA28 instead and is not touched here.
constexpr int battle_track = 0xD;

// Resuming the field track where it left off.
//
// Where the ALCSeq is comes from func_80025364, the routine that starts a
// track: it works out a 0x19C-byte block per player from 0x8008F978, then
// calls alCSeqNew (0x80038AEC) with `block + 0x98` and the sequence buffer
// at `block + 0x190`, and alSeqpSetSeq with the player at `block + 0x1C`.
// So the ALCSeq is embedded in that block at +0x98, and the player - the
// same 0x8008F994 alCSPNew was handed in func_8002513C - at +0x1C.
//
// alCSeqNew (0x80038AEC) gives the rest of the layout: +0x00 the buffer the
// sequence was read into, +0x04 validTracks (a bit per track that has an
// offset in the file's header), +0x08 1/division as a float, and the 16 read
// pointers at +0x18, one word each.
//
// The two halves of a seek are in the ROM but dead - nothing in the game
// calls either. func_80038590 copies sequence -> marker (alCSeqGetLoc) and
// func_80038630 copies marker -> sequence (alCSeqSetLoc); they are mirrors
// of each other, both walking the 16 tracks two at a time. Both are leaf
// functions with no prologue, so they can be called with a scratch context
// and no stack of their own.
//
// The marker holds pointers into the sequence buffer. That is safe across a
// battle because the field track is re-read into the same buffer at the same
// address, so the bytes those pointers name are the same bytes again.
constexpr int32_t bgm_block = 0x8008F978;
constexpr int32_t bgm_player = bgm_block + 0x1C;    // 0x8008F994
constexpr int32_t bgm_sequence = bgm_block + 0x98;  // 0x8008FA10
constexpr uint32_t marker_size = 0x100;   // ALCSeqMarker is about 0xA0

// The track func_80026658 will start next. Both UpdateBGM and the map
// music routine write it here, which is why it is what gets watched.
constexpr int32_t bgm_requested_track = 0x8008FCC1;
int last_requested = -2;
int32_t marker_block = 0;
int saved_track = -1;
bool have_saved = false;
// Waiting to put the position back. UpdateBGM does not start anything - it
// only writes the wanted track to 0x8008FCC1 and raises a flag - and
// func_80026658 does the load and the play some frames later. So the restore
// cannot be counted in frames from the request, or it lands before the
// sequence exists and the load wipes it. It waits for the track to actually
// be playing instead.
bool restore_waiting = false;
int restore_settle = 0;

namespace {
    // The heap block the marker sat in is gone after a relaunch, and none of
    // the watched state means anything for the new run.
    void reset_resume_state() {
        marker_block = 0;
        last_requested = -2;
        saved_track = -1;
        have_saved = false;
        restore_waiting = false;
        restore_settle = 0;
    }
}

std::ofstream resume_log;
void resume_note(const std::string& line) {
    if (!resume_log.is_open()) {
        resume_log.open(zelda64::get_app_folder_path() / "battle_music.txt");
    }
    resume_log << line << "\n";
    resume_log.flush();
}

int32_t marker_address(uint8_t* rdram) {
    if (marker_block == 0) {
        void* mem = recomp::alloc(rdram, marker_size);
        if (mem == nullptr) {
            return 0;
        }
        uint32_t offset = static_cast<uint32_t>(reinterpret_cast<uint8_t*>(mem) - rdram);
        marker_block = static_cast<int32_t>(offset + 0x80000000u);
    }
    return marker_block;
}

void seek_call(uint8_t* rdram, void (*fn)(uint8_t*, recomp_context*), int32_t marker) {
    recomp_context scratch{};
    scratch.r4 = S32(bgm_sequence);
    scratch.r5 = S32(marker);
    fn(rdram, &scratch);
}

// UpdateBGM (0x800267B8) and func_800267F8, before anything else: true means
// the hook swallows the whole call and the music carries on untouched.
//
// Keeping the field music through a fight takes two refusals, not one. The
// obvious half is refusing to start the battle track. The other is refusing
// the restore afterwards: the game ends a battle by asking for the map's
// track again, and since that track never actually stopped, honouring it
// would restart it from the beginning - which is the very jolt the option
// exists to avoid.
extern "C" int quest64_audio_skip_bgm(uint8_t* rdram, recomp_context* ctx) {
    int mode = zelda64::audio::active_options().battle_music;
    int wanted = static_cast<int8_t>(ctx->r4 & 0xFF);

    if (mode == 1 && wanted == battle_track) {
        // Refusing this is the whole trick. Both routines that start music
        // compare what is asked for against the track already on record at
        // 0x8008FCC1, so leaving the field track on record means the
        // restore after the fight is dropped by the game itself.
        return 1;
    }

    return 0;
}

// From audio::on_frame. The sequence is only loaded and running a frame or
// two after the request, so the jump back waits for it.
// Resuming is driven from here rather than from a hook, because the hook
// cannot see what it needs to. UpdateBGM is not how the field music starts:
// func_8002684C, which picks a map's track, writes the track to 0x8008FCC1
// and raises the flag itself without calling UpdateBGM at all. So the only
// thing both paths have in common is that byte, and watching it is the only
// way to notice a battle beginning and ending.
//
// This runs at the top of func_80026658, before that routine acts on the
// flag, which is exactly the right moment: when the byte has just turned to
// the battle track the field sequence is still loaded and playing, so its
// position can still be read.
void tick_resume(uint8_t* rdram) {
    if (zelda64::audio::active_options().battle_music != 2) {
        return;
    }

    int requested = static_cast<int8_t>(MEM_B(0, bgm_requested_track));
    if (requested != last_requested) {
        int previous = last_requested;
        last_requested = requested;

        if (requested == battle_track && previous >= 0 && previous != battle_track) {
            if (int32_t marker = marker_address(rdram)) {
                seek_call(rdram, func_80038590, marker);
                // Never put back a position that was not read from a live
                // sequence: the seek would write nonsense into it and leave
                // the player mid-event, which sounds like one note stuck on.
                // Dropping the save is the harmless failure - the track just
                // restarts from the top, as it does normally.
                //
                // alCSeqGetLoc copies the sequence's fields in its own order,
                // so the marker is not laid out like the ALCSeq: the first
                // word is validTracks and the 16 read pointers follow at
                // +0xC. A save is good when every track validTracks claims
                // is reading somewhere inside the sequence buffer.
                uint32_t valid = static_cast<uint32_t>(MEM_W(0, marker)) & 0xFFFF;
                uint32_t buffer = static_cast<uint32_t>(seq_buffers[0]);
                bool sane = valid != 0 && buffer != 0;
                for (int track = 0; track < 16 && sane; track++) {
                    if ((valid & (1u << track)) == 0) {
                        continue;
                    }
                    uint32_t at = static_cast<uint32_t>(MEM_W(0, marker + 0xC + track * 4));
                    sane = at >= buffer && at < buffer + seq_buffer_size;
                }
                saved_track = previous;
                have_saved = sane;
                char note[192];
                std::snprintf(note, sizeof note,
                              "battle started: track %d, validTracks 0x%04X, buffer 0x%08X %s",
                              saved_track, valid, buffer,
                              sane ? "- saved" : "- read pointers outside the buffer, resume skipped");
                resume_note(note);
            }
        }
        else if (have_saved && requested == saved_track) {
            restore_waiting = true;
            restore_settle = 0;
            have_saved = false;
            resume_note("battle over: waiting for track " + std::to_string(saved_track) + " to start again");
        }
    }

    if (!restore_waiting || marker_block == 0) {
        return;
    }
    // func_80026658 copies the track to 0x8008FCC0 just before it loads the
    // sequence, so seeing it there means the load has happened.
    int playing = static_cast<int8_t>(MEM_B(0, bgm_current_track));
    if (playing != saved_track) {
        restore_settle = 0;
        return;
    }
    if (++restore_settle < 2) {
        return;
    }
    seek_call(rdram, func_80038630, marker_block);
    restore_waiting = false;
    resume_note("restored: track " + std::to_string(saved_track) + " put back to where it was");
}

// func_800263A8: the second sequence player, used for jingles started by
// number (a0 is the track).
extern "C" void quest64_audio_jingle(uint8_t*, recomp_context* ctx) {
    if (zelda64::audio::active_options().music_shuffle != MusicShuffle::All) {
        return;
    }
    int track = static_cast<int32_t>(ctx->r4);
    if (usable_track(track)) {
        ctx->r4 = S32(bgm_remap[track]);
    }
}

// func_80025B8C: the routine every sound effect ends in, queued or not,
// with the effect id in a0 (volume in a1, 0x40 in a2). A volume of zero is
// a stop request (func_80025B3C), left alone.
extern "C" void quest64_audio_sfx(uint8_t*, recomp_context* ctx) {
    if (!zelda64::audio::active_options().sfx_shuffle) {
        return;
    }
    int32_t id = static_cast<int32_t>(ctx->r4);
    if (id < 0 || id >= sfx_count) {
        return;
    }
    if (static_cast<int32_t>(ctx->r5) == 0) {
        return;
    }
    int played = sfx_remap[id];
    ctx->r4 = S32(played);
    sfx_started[played] = sfx_clock::now();
    sfx_live[played] = true;
}

// Once per frame from the cheats frame hook: cut whatever has been going
// for three seconds since it last started.
std::string zelda64::audio::song_name(int track) {
    auto it = session_songs.find(track);
    if (it != session_songs.end()) {
        int own = game_track_of(it->second);
        return own >= 0 ? track_label(own) : it->second;
    }
    return track_label(track);
}

int zelda64::audio::game_track_of(const std::string& name) {
    if (name.compare(0, game_prefix.size(), game_prefix) != 0) {
        return -1;
    }
    int track = std::atoi(name.c_str() + game_prefix.size());
    return track >= 0 && track < game_track_count ? track : -1;
}

void zelda64::audio::apply_tracks_live(const std::map<int, std::string>& tracks) {
    std::lock_guard lock(live_mutex);
    pending_entries.clear();
    for (int track = 0; track < game_track_count; track++) {
        auto it = tracks.find(track);
        pending_entries[track] = it != tracks.end() ? it->second : std::string();
    }
    pending_all = true;
}

void zelda64::audio::preview_track(int track) {
    std::lock_guard lock(live_mutex);
    pending_preview = track < 0 ? -1 : track;
}

bool zelda64::audio::library_loaded() {
    return library_in_rom;
}

void zelda64::audio::set_custom_volume_live(int percent) {
    custom_volume_live = std::clamp(percent, 10, 100);
    custom_volume_dirty = true;
}

// func_80026554: a0 is the music volume level (0-255) about to be set on
// both sequence players. Scaled while the main player's track is a custom
// file (a game:N choice is the game's own music and is left alone).
//
// Two scales, not one. The song's own gain brings it level with the game's
// music, which is per file and automatic; the slider then sets how loud
// custom music sits against the game's as a whole, which is a taste and is
// the same for every file.
extern "C" void quest64_audio_music_volume(uint8_t* rdram, recomp_context* ctx) {
    int track = static_cast<int8_t>(MEM_B(0, bgm_current_track));
    auto it = session_songs.find(track);
    if (it == session_songs.end() || zelda64::audio::game_track_of(it->second) >= 0) {
        return;
    }
    int percent = custom_volume_live >= 0 ? custom_volume_live.load() : zelda64::audio::active_options().custom_volume;
    float level = static_cast<int32_t>(ctx->r4 & 0xFF) * (percent / 100.0f) * custom_gain(it->second);
    ctx->r4 = S32(std::clamp(static_cast<int32_t>(level + 0.5f), 0, 255));
}

void zelda64::audio::on_frame(uint8_t* rdram, recomp_context* ctx) {
    tick_resume(rdram);
    // The menu's live changes: table entries, then a preview request.
    if (library_in_rom) {
        std::map<int, std::string> entries;
        int preview = -2;
        {
            std::lock_guard lock(live_mutex);
            if (pending_all) {
                entries.swap(pending_entries);
                pending_all = false;
            }
            preview = pending_preview;
            pending_preview = -2;
        }
        for (const auto& [track, name] : entries) {
            write_live_entry(rdram, track, name);
        }
        int requested = static_cast<int8_t>(MEM_B(0, bgm_request_track));
        if (preview >= 0) {
            if (preview_return == -2) {
                preview_return = static_cast<int8_t>(MEM_B(0, bgm_current_track));
            }
            if (requested == preview) {
                // The track already requested: stop this frame, start next.
                request_track(rdram, -1);
                std::lock_guard lock(live_mutex);
                pending_preview = preview;
            }
            else {
                request_track(rdram, preview);
                watch_track = preview;
                watch_frames = 0;
            }
        }
        else if (preview == -1 && preview_return != -2) {
            request_track(rdram, preview_return);
            preview_return = -2;
            watch_track = -1;
        }
        if (watch_track >= 0) {
            int flags = MEM_HU(0, bgm_request_flags);
            int state = static_cast<int32_t>(MEM_W(0, seq_player_state));
            int current = static_cast<int8_t>(MEM_B(0, bgm_current_track));
            if (state != 0 && current == watch_track) {
                watch_track = -1;   // playing: done
                watch_retries = 0;
            }
            else if (++watch_frames > 90) {
                bool idle = (flags & 7) == 0 && MEM_HU(0, bgm_request_timer) == 0;
                live_log << "  preview of track " << watch_track << " did not start (state " << state << ", current "
                         << current << ", flags 0x" << std::hex << flags << std::dec << ")";
                if (idle && watch_retries < 2) {
                    live_log << "; asking again\n";
                    watch_retries++;
                    watch_frames = 0;
                    request_track(rdram, -1);
                    std::lock_guard lock(live_mutex);
                    pending_preview = watch_track;
                }
                else {
                    live_log << "; giving up\n";
                    watch_track = -1;
                    watch_retries = 0;
                }
                live_log.flush();
            }
        }
    }

    if (song_notice_countdown > 0 && --song_notice_countdown == 0 && song_notice_track >= 0) {
        // Still the track that started, or it was replaced meanwhile.
        int now = static_cast<int8_t>(MEM_B(0, bgm_current_track));
        if (now == song_notice_track) {
            zelda64::notify::post("Now playing: " + song_name(song_notice_track), zelda64::notify::Kind::Song);
        }
        song_notice_track = -1;
    }

    // The custom music volume changed in the menu: have the game set the
    // players' volume again, through the hooked routine.
    if (custom_volume_dirty.exchange(false) && ctx != nullptr) {
        recomp_context copy = *ctx;
        func_80026A04(rdram, &copy);
    }

    // "Show song name" (Layout tab): a line whenever the main player
    // starts a track.
    int track = static_cast<int8_t>(MEM_B(0, bgm_current_track));
    if (track != last_seen_track) {
        bool announce = last_seen_track != -2 && track >= 0 && track < game_track_count
            && zelda64::enhancements::active_options().song_notice;
        last_seen_track = track;
        if (announce) {
            song_notice_track = track;
            song_notice_countdown = song_notice_delay;
        }
        // Diagnostics: what the player was handed for this track.
        if (library_in_rom && track >= 0 && track < game_track_count) {
            int32_t table = static_cast<int32_t>(MEM_W(0, seq_table_pointer));
            int32_t player = 0x8008F978;
            int32_t buffer = static_cast<int32_t>(MEM_W(0, player + 0x190));
            live_log << "  start: track " << track << " entry 0x" << std::hex
                     << static_cast<uint32_t>(MEM_W(0, table + 4 + track * 8)) << " len 0x"
                     << static_cast<uint32_t>(MEM_W(0, table + 8 + track * 8)) << " buffer 0x" << buffer << ":";
            for (int i = 0; i < 24; i++) {
                live_log << " " << static_cast<int>(MEM_BU(0, buffer + i));
            }
            live_log << std::dec << "\n";
            live_log.flush();
        }
    }

    if (!active_options().sfx_shuffle) {
        return;
    }
    sfx_clock::time_point now = sfx_clock::now();
    for (int id = 0; id < sfx_count; id++) {
        if (!sfx_live[id]) {
            continue;
        }
        if (std::chrono::duration<float>(now - sfx_started[id]).count() >= sfx_cutoff_seconds) {
            queue_sfx_stop(rdram, id);
            sfx_live[id] = false;
        }
    }
}
