# Generated by tools/archipelago_world.pl. Do not edit by hand.
# The names and ids come from Quest64Checks.pm, which DOCS/archipelago_checks.xlsx
# is also built from, so this file and that sheet cannot disagree.
from typing import Dict, List, Tuple

# The regions a monster can be in, earliest first. Each needs everything
# the one before it does.
REGION_ORDER: List[str] = ["Overworld", "Early", "Boss 2", "Mid", "Boss 4", "Late", "Endgame"]

# The game's sixteen progression areas, in its order: name, logic region, and
# how many monsters its packs can hold.
ENEMY_AREAS: List[Tuple[str, str, int]] = [
    ("Holy Plains", "Overworld", 12),
    ("Connor Forest", "Overworld", 14),
    ("Dondoran Flats", "Boss 2", 14),
    ("Glencoe Forest", "Boss 2", 8),
    ("West Carmaugh", "Mid", 20),
    ("Cull Hazard", "Boss 2", 12),
    ("East Limelin", "Boss 4", 17),
    ("Windward Forest", "Boss 2", 17),
    ("Blue Cave", "Mid", 13),
    ("Isle of Skye", "Mid", 10),
    ("Baragoon Tunnel", "Boss 4", 12),
    ("Dindom Dries", "Boss 4", 16),
    ("Boil Hole", "Boss 4", 13),
    ("Baragoon Moor", "Late", 14),
    ("Brannoch Castle", "Late", 4),
    ("Mammon's World", "Endgame", 6),
]

# The monsters of each of the six monster files, by global id.
FILE_MONSTERS: List[List[int]] = [
    [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
    [27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37],
    [38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62],
    [63, 64, 65, 66],
]

# Each monster's location.
ENEMY_LOCATIONS: Dict[int, str] = {
    0: "Defeat - Were Hare",
    1: "Defeat - Hell Hound",
    2: "Defeat - Man Eater",
    3: "Defeat - Big Mouth",
    4: "Defeat - Bumbershoot",
    5: "Defeat - Parasault",
    6: "Defeat - Ork Jr",
    7: "Defeat - Gremlin",
    8: "Defeat - Skeleton",
    9: "Defeat - Ghosthound",
    10: "Defeat - Merrow",
    11: "Defeat - Wolf Goat",
    12: "Defeat - Goblin",
    13: "Defeat - Frog King",
    14: "Defeat - Apophis",
    15: "Defeat - Mad Doll",
    16: "Defeat - Death Hugger",
    17: "Defeat - Kobold",
    18: "Defeat - Man Trap",
    19: "Defeat - Bat",
    20: "Defeat - Frog Knight",
    21: "Defeat - Marionasty",
    22: "Defeat - Dark Goblin",
    23: "Defeat - Hot Lips",
    24: "Defeat - Ghost Stalker",
    25: "Defeat - Treant",
    26: "Defeat - Cockatrice",
    27: "Defeat - Multi Optics",
    28: "Defeat - Mimic",
    29: "Defeat - Crawler",
    30: "Defeat - Scorpion",
    31: "Defeat - Scare Crow",
    32: "Defeat - Wyvern",
    33: "Defeat - Skelebat",
    34: "Defeat - Cryshell",
    35: "Defeat - Blood Jell",
    36: "Defeat - Caterpillar",
    37: "Defeat - Fish Man",
    38: "Defeat - Sandman",
    39: "Defeat - Were Cat",
    40: "Defeat - Nightmare",
    41: "Defeat - Blue Man",
    42: "Defeat - Winged Sunfish",
    43: "Defeat - Gloom Wing",
    44: "Defeat - Ogre",
    45: "Defeat - Rocky",
    46: "Defeat - Red Wyvern",
    47: "Defeat - Flamed Mane",
    48: "Defeat - Magma Fish",
    49: "Defeat - Red Rose Knight",
    50: "Defeat - White Rose Knight",
    51: "Defeat - Ork",
    52: "Defeat - Ghost",
    53: "Defeat - Will-o'-wisp",
    54: "Defeat - Sprite",
    55: "Defeat - Jack-o'-lantern",
    56: "Defeat - Arachnoid",
    57: "Defeat - Lamia",
    58: "Defeat - Temptress",
    59: "Defeat - Pixie",
    60: "Defeat - Grangach",
    61: "Defeat - Thunder Jell",
    62: "Defeat - Termant",
    63: "Defeat - Judgment",
    64: "Defeat - Pale Rider",
    65: "Defeat - Pin Head",
    66: "Defeat - Spriggan",
}
ENEMY_IDS: Dict[str, int] = {name: gid for gid, name in ENEMY_LOCATIONS.items()}
