# Generated by tools/archipelago_world.pl. Do not edit by hand.
# The names and ids come from Quest64Checks.pm, which DOCS/archipelago_checks.xlsx
# is also built from, so this file and that sheet cannot disagree.
from typing import Callable, Dict, NamedTuple, Optional

from BaseClasses import Item, ItemClassification


class Q64Item(Item):
    game = "Quest 64 Recompiled"


class Q64ItemData(NamedTuple):
    code: Optional[int] = None
    type: ItemClassification = ItemClassification.filler
    num_exist: int = 1
    can_create: Callable = lambda options: True


item_data_table: Dict[str, Q64ItemData] = {
    "Level Up": Q64ItemData(code=0x51640F00, type=ItemClassification.progression, num_exist=98, can_create=lambda options: bool(options.spiritsanity) or options.extra_level_ups.value > 0),
    "Solvaring's Soul": Q64ItemData(code=0x51640E01, type=ItemClassification.progression, num_exist=1, can_create=lambda options: options.boss_souls.value >= 1),
    "Zelse's Soul": Q64ItemData(code=0x51640E02, type=ItemClassification.progression, num_exist=1, can_create=lambda options: options.boss_souls.value >= 1),
    "Nepty's Soul": Q64ItemData(code=0x51640E03, type=ItemClassification.progression, num_exist=1, can_create=lambda options: options.boss_souls.value >= 1),
    "Shilf's Soul": Q64ItemData(code=0x51640E04, type=ItemClassification.progression, num_exist=1, can_create=lambda options: options.boss_souls.value >= 1),
    "Fargo's Soul": Q64ItemData(code=0x51640E05, type=ItemClassification.progression, num_exist=1, can_create=lambda options: options.boss_souls.value >= 1),
    "Guilty's Soul": Q64ItemData(code=0x51640E06, type=ItemClassification.progression, num_exist=1, can_create=lambda options: options.boss_souls.value >= 1),
    "Beigis's Soul": Q64ItemData(code=0x51640E07, type=ItemClassification.progression, num_exist=1, can_create=lambda options: options.boss_souls.value >= 1),
    "Mammon's Soul": Q64ItemData(code=0x51640E08, type=ItemClassification.progression, num_exist=1, can_create=lambda options: options.boss_souls.value >= 2),
    "Spirit Light": Q64ItemData(code=0x51640000, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Fresh Bread": Q64ItemData(code=0x51640001, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Honey Bread": Q64ItemData(code=0x51640002, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Healing Potion": Q64ItemData(code=0x51640003, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Dragon's Potion": Q64ItemData(code=0x51640004, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Dew Drop": Q64ItemData(code=0x51640005, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Mint Leaves": Q64ItemData(code=0x51640006, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Heroes Drink": Q64ItemData(code=0x51640007, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Silent Flute": Q64ItemData(code=0x51640008, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Celine's Bell": Q64ItemData(code=0x51640009, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Replica": Q64ItemData(code=0x5164000A, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Giant's Shoes": Q64ItemData(code=0x5164000B, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Silver Amulet": Q64ItemData(code=0x5164000C, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "Golden Amulet": Q64ItemData(code=0x5164000D, type=ItemClassification.filler, num_exist=0, can_create=lambda options: True),
    "White Wings": Q64ItemData(code=0x5164000E, type=ItemClassification.useful, num_exist=2, can_create=lambda options: True),
    "Yellow Wings": Q64ItemData(code=0x5164000F, type=ItemClassification.useful, num_exist=2, can_create=lambda options: True),
    "Blue Wings": Q64ItemData(code=0x51640010, type=ItemClassification.useful, num_exist=2, can_create=lambda options: True),
    "Green Wings": Q64ItemData(code=0x51640011, type=ItemClassification.useful, num_exist=2, can_create=lambda options: True),
    "Red Wings": Q64ItemData(code=0x51640012, type=ItemClassification.useful, num_exist=2, can_create=lambda options: True),
    "Black Wings": Q64ItemData(code=0x51640013, type=ItemClassification.useful, num_exist=2, can_create=lambda options: True),
    "Earth Orb": Q64ItemData(code=0x51640014, type=ItemClassification.progression, num_exist=1, can_create=lambda options: True),
    "Wind Jade": Q64ItemData(code=0x51640015, type=ItemClassification.progression, num_exist=1, can_create=lambda options: True),
    "Water Jewel": Q64ItemData(code=0x51640016, type=ItemClassification.progression, num_exist=1, can_create=lambda options: True),
    "Fire Ruby": Q64ItemData(code=0x51640017, type=ItemClassification.progression, num_exist=1, can_create=lambda options: True),
    "Eletale's Book": Q64ItemData(code=0x51640018, type=ItemClassification.progression, num_exist=1, can_create=lambda options: True),
    "Dark Gaol Key": Q64ItemData(code=0x51640019, type=ItemClassification.progression, num_exist=1, can_create=lambda options: True),
}

item_table: Dict[str, int] = {name: data.code for name, data in item_data_table.items() if data.code is not None}
code_to_item_table: Dict[int, str] = {code: name for name, code in item_table.items()}
filler_items = [name for name, data in item_data_table.items() if data.type == ItemClassification.filler]
