# Generated by tools/archipelago_world.pl from DOCS/archipelago_logic.xlsx.
# Change the logic in that workbook, not here.
from typing import List, Tuple


# Every region, Menu first: Archipelago starts there.
regions: List[str] = [
    "Menu",
    "Overworld",
    "Boss 1",
    "Early",
    "Boss 2",
    "Boss 3",
    "Mid",
    "Boss 4",
    "Boss 5",
    "Late",
    "Boss 6",
    "Boss 7",
    "Endgame",
    "Boss 8",
]

# (from, to). The entrance between them is named "<from> to <to>", which is
# the name world.get_entrance() and the rules use.
connections: List[Tuple[str, str]] = [
    ("Menu", "Overworld"),
    ("Overworld", "Boss 1"),
    ("Overworld", "Early"),
    ("Boss 1", "Boss 2"),
    ("Early", "Boss 2"),
    ("Boss 2", "Boss 3"),
    ("Boss 3", "Mid"),
    ("Boss 3", "Boss 4"),
    ("Mid", "Boss 5"),
    ("Boss 4", "Boss 5"),
    ("Boss 5", "Late"),
    ("Boss 5", "Boss 6"),
    ("Late", "Boss 7"),
    ("Boss 6", "Boss 7"),
    ("Boss 7", "Endgame"),
    ("Endgame", "Boss 8"),
]
