# Generated by tools/archipelago_world.pl from DOCS/archipelago_logic.xlsx.
# Change the logic in that workbook, not here.
from __future__ import annotations

from typing import TYPE_CHECKING, Dict

from rule_builder.options import OptionFilter
from rule_builder.rules import CanReachLocation, CanReachRegion, Has, Rule

from .Options import BossSouls, MammonPortal

if TYPE_CHECKING:
    from . import Q64World

# Rules used in more than one place (the Named Rules sheet).
EARTH_ORB_GATE: Rule = Has("Earth Orb") | OptionFilter(BossSouls, 1, operator="ge")
WIND_JADE_GATE: Rule = Has("Wind Jade") | OptionFilter(BossSouls, 1, operator="ge")
WATER_JEWEL_GATE: Rule = Has("Water Jewel") | OptionFilter(BossSouls, 1, operator="ge")
FIRE_RUBY_GATE: Rule = Has("Fire Ruby") | OptionFilter(BossSouls, 1, operator="ge")
ALL_BOSSES_BEATEN: Rule = CanReachLocation("Boss - Solvaring") & CanReachLocation("Boss - Zelse") & CanReachLocation("Boss - Nepty") & CanReachLocation("Boss - Shilf") & CanReachLocation("Boss - Fargo") & CanReachLocation("Boss - Guilty") & CanReachLocation("Boss - Beigis")
ALL_MONSTER_AREAS: Rule = CanReachRegion("Overworld") & CanReachRegion("Early") & CanReachRegion("Mid") & CanReachRegion("Late")
ENDGAME_DOOR: Rule = (OptionFilter(MammonPortal, 0) & Has("Eletale's Book")) | (OptionFilter(MammonPortal, 1) & ALL_BOSSES_BEATEN) | (OptionFilter(MammonPortal, 2) & ALL_MONSTER_AREAS) | (OptionFilter(MammonPortal, 3) & ALL_BOSSES_BEATEN & ALL_MONSTER_AREAS)

# The Entrances sheet. An entrance with no rule is always open.
entrance_rules: Dict[str, Rule] = {
    "Boss 1 to Boss 2": EARTH_ORB_GATE,
    "Early to Boss 2": EARTH_ORB_GATE,
    "Boss 2 to Boss 3": WIND_JADE_GATE,
    "Boss 3 to Mid": WIND_JADE_GATE,
    "Boss 3 to Boss 4": WATER_JEWEL_GATE,
    "Mid to Boss 5": WATER_JEWEL_GATE,
    "Boss 4 to Boss 5": WATER_JEWEL_GATE,
    "Boss 5 to Late": FIRE_RUBY_GATE,
    "Boss 5 to Boss 6": FIRE_RUBY_GATE,
    "Late to Boss 7": FIRE_RUBY_GATE,
    "Boss 6 to Boss 7": FIRE_RUBY_GATE,
    "Boss 7 to Endgame": ENDGAME_DOOR,
    "Endgame to Boss 8": Has("Dark Gaol Key"),
}

# The Locations sheet, where reaching the region is not enough.
location_rules: Dict[str, Rule] = {
    "Boss - Solvaring": Has("Solvaring's Soul") | OptionFilter(BossSouls, 0),
    "Boss - Zelse": Has("Zelse's Soul") | OptionFilter(BossSouls, 0),
    "Boss - Nepty": Has("Nepty's Soul") | OptionFilter(BossSouls, 0),
    "Boss - Shilf": Has("Shilf's Soul") | OptionFilter(BossSouls, 0),
    "Boss - Fargo": Has("Fargo's Soul") | OptionFilter(BossSouls, 0),
    "Boss - Guilty": Has("Guilty's Soul") | OptionFilter(BossSouls, 0),
    "Boss - Beigis": Has("Beigis's Soul") | OptionFilter(BossSouls, 0),
    "Boss - Mammon": Has("Mammon's Soul") | OptionFilter(BossSouls, 2, operator="lt"),
}

# The Guide sheet's completion rule.
completion_rule: Rule = CanReachLocation("Boss - Mammon")


def set_all_rules(world: Q64World) -> None:
    multiworld, player = world.multiworld, world.player
    for name, rule in entrance_rules.items():
        world.set_rule(multiworld.get_entrance(name, player), rule)
    # A location the options switched off does not exist, and has no rule
    # to set.
    present = {location.name for location in multiworld.get_locations(player)}
    for name, rule in location_rules.items():
        if name in present:
            world.set_rule(multiworld.get_location(name, player), rule)
    world.set_completion_rule(completion_rule)
