#ifndef __BOSS_SPELLS_H__
#define __BOSS_SPELLS_H__

#include <cstdint>
#include <string>
#include <vector>

// The seventeen spells the bosses cast, and the two extra spell categories
// the replacement logic needs. Generated by tools/extract_boss_spells.pl;
// see boss_spells.cpp and randomizer.cpp's place_boss_spells().
namespace merrow::data {
    struct BossSpell {
        // What the spoiler calls it, and the label the ROM itself uses.
        const char* name;
        const char* label;
        // The 0x44-byte spell record and the 0x48-byte animation record.
        uint32_t data_address;
        uint32_t anim_address;
        const char* data;
        const char* anim;
        // False for the spells that only work cast by a boss, which are
        // never handed to Brian.
        bool castable;
    };

    extern const std::vector<BossSpell> bossSpells;
    extern const std::vector<int> buffSpells;
    extern const std::vector<int> debuffSpells;

    // The player spells' animation records, which sit in one table with the
    // bosses' at the same stride as the spell records.
    constexpr uint32_t spell_anim_start = 0xD4D338;
    constexpr uint32_t spell_anim_size = 0x48;
}

#endif
