#ifndef __CHEST_DATA_H__
#define __CHEST_DATA_H__

#include <cstdint>
#include <vector>

// The game's 88 chests and the places one can be put.
// Generated by tools/extract_chests.pl; see that script and chest_data.cpp.
namespace merrow::chests {
    struct Chest {
        uint8_t map;
        uint8_t submap;
        // The save flag's bit, 0-87, and what is inside.
        uint8_t id;
        uint32_t rom;
        uint8_t item;
        // Where it is in vanilla, so a chest that is not moved can stay put.
        float x;
        float z;
        float facing;
        float ox;
        float oz;
    };

    // How a spot's facing was arrived at: Vanilla is the game's own, Spirit
    // is aimed at the nearest other known-walkable point in the room. A third
    // kind, interpolated between walkable points, was tried and removed - it
    // put a chest inside a fence.
    enum class Kind : uint8_t { Vanilla, Spirit };

    struct Spot {
        uint8_t map;
        uint8_t submap;
        float x;
        float z;
        // A chest faces (sin, cos) of this, and ox/oz is where Brian stands
        // to open it - six units along that direction.
        float facing;
        float ox;
        float oz;
        Kind kind;
        bool outdoor;
    };

    extern const std::vector<Chest> chests;
    extern const std::vector<Spot> spots;
    // Submaps per map, so a relocated per-submap array covers every index
    // the placement routine can reach (it does not bounds-check the submap).
    extern const std::vector<uint8_t> map_submap_counts;

    // The outer table func_80011B70 walks: 19 entries of { u32 map, u32
    // per-submap array }, the per-submap array 8 bytes an entry of
    // { u16 count, u16 pad, u32 records }, and a record 36 bytes.
    constexpr int32_t table_address = 0x8004C470;
    constexpr int map_slots = 19;
    constexpr int chest_count = 88;
    constexpr uint32_t map_slot_size = 8;
    constexpr uint32_t submap_entry_size = 8;
    // The placement routine indexes the per-submap array by submap without a
    // bounds check, so a relocated one is given room for more submaps than
    // any map has (the widest is 26).
    constexpr int submap_slots = 32;
    constexpr uint32_t record_size = 36;
    // Copied into every relocated record; the vanilla chests all carry one
    // of these two and the difference is not worth tracking per spot.
    constexpr float extent = 4.0f;
}

#endif
