#ifndef __SPIRIT_DATA_H__
#define __SPIRIT_DATA_H__

#include <cstdint>
#include <vector>

// Where the game's spirits are, and everywhere else one could stand.
// Generated by tools/extract_spirits.pl; see that script and spirit_data.cpp.
namespace merrow::spirits {
    // One of the 43 entries of the table func_80012220 reads at map load.
    struct Slot {
        uint8_t map;
        uint8_t submap;
        uint8_t count;
    };

    // Where a spot came from, which is how far it can be trusted: Spirit is
    // one the game already floats a spirit on, Entrance one it stands Brian
    // on, and Made a point off the short line between two of those.
    enum class Kind : uint8_t { Spirit, Entrance, Made };

    // A place a spirit can be put: an x and a z in a submap, which the game
    // drops onto the ground itself.
    struct Spot {
        uint8_t map;
        uint8_t submap;
        float x;
        float z;
        Kind kind;
    };

    extern const std::vector<Slot> vanilla_slots;
    extern const std::vector<Spot> spots;

    // The spirit table, in the boot segment and so resident from the start:
    // 43 entries of { u16 map, u16 submap, u16 count, u16 pad, u32 records },
    // each record 12 bytes of { f32 x, f32 z, u8 id, u8 pad[3] }.
    constexpr int32_t table_address = 0x8004C510;
    constexpr int slot_count = 43;
    constexpr int spirit_count = 98;
    constexpr uint32_t slot_size = 12;
    constexpr uint32_t record_size = 12;
}

#endif
