#!/usr/bin/perl
# Generates the inputs for recompiling the Hard Mode payload:
#
#   Quest64Syms/hardmode_syms.toml  the game's dump.toml plus a section for the
#                                   payload the hack appends to the ROM
#   hardmode.toml                   N64Recomp config that recompiles only that
#                                   section (every game function is "ignored",
#                                   which keeps it resolvable as a call target
#                                   without emitting it a second time)
#
#   perl tools/hardmode/gen_syms.pl
#   N64Recomp.exe hardmode.toml
#
# The function list comes from tools/hardmode/payload_funcs.txt, which was
# produced by following control flow from every address the game's patched
# code jumps to and every jal/j target inside the payload's C code. Hand
# written asm shims (0x80410000-0x80410C7C) are not listed: they end by
# jumping into the middle of game functions, which cannot be recompiled, so
# src/game/hardmode/hooks.cpp reproduces them natively instead.
use strict;
use warnings;
use FindBin;

my $root = "$FindBin::Bin/../..";
my $dump = "$root/Quest64Syms/dump.toml";
# The names N64Recomp actually emits: it renames some libultra functions
# (__ll_div -> __ll_div_recomp), and "ignored" is matched against those.
my $funcs_h = "$root/RecompiledFuncs/funcs.h";
my $list = "$FindBin::Bin/payload_funcs.txt";

open my $in, '<', $dump or die "$dump: $!";
my @dump = <$in>;
close $in;

open my $fh, "<", $funcs_h or die "$funcs_h: $! (run N64Recomp.exe us.rev0.toml first)";
my %emitted;
while (<$fh>) {
    $emitted{$1} = 1 if /^void (\w+)\(uint8_t\* rdram, recomp_context\* ctx\);/;
}
close $fh;
my @names;
for (@dump) {
    next unless /name = "([^"]+)", vram = 0x[0-9A-Fa-f]+, size = 0x[0-9A-Fa-f]+/;
    # Functions absent from funcs.h are libultra ones N64Recomp handles
    # itself; naming those in "ignored" is an error.
    if ($emitted{"$1_recomp"}) {
        push @names, "$1_recomp";
    } elsif ($emitted{$1}) {
        push @names, $1;
    }
}

open my $fl, '<', $list or die "$list: $!";
my @funcs;
while (<$fl>) {
    next unless /^([0-9A-Fa-f]{8})\s+([0-9A-Fa-f]+)/;
    push @funcs, [ hex $1, hex $2 ];
}
close $fl;

open my $out, '>', "$root/Quest64Syms/hardmode_syms.toml" or die $!;
print $out "# Generated by tools/hardmode/gen_syms.pl: Quest64Syms/dump.toml followed by\n";
print $out "# the Hard Mode payload section. Do not edit by hand.\n";
print $out @dump;
print $out "\n[[section]]\n";
print $out "name = \".hardmode\"\n";
print $out "rom = 0x01000000\n";
print $out "vram = 0x80400000\n";
print $out "size = 0x1CF54\n\n";
print $out "functions = [\n";
for my $f (@funcs) {
    printf $out "    { name = \"hm_func_%08X\", vram = 0x%08X, size = 0x%X },\n", $f->[0], $f->[0], $f->[1];
}
print $out "]\n";
close $out;

open my $cfg, '>', "$root/hardmode.toml" or die $!;
print $cfg <<'EOF';
# Generated by tools/hardmode/gen_syms.pl. Recompiles the code the Hard Mode
# hack appends to the ROM (RAM 0x80400000), out of quest64.hm.z64, which is
# quest64.us.z64 with tools/hardmode/Quest64.HM.*.rup applied by
# tools/hardmode/apply_rup.pl. The output is checked in under
# src/game/hardmode/recompiled/ so a normal build needs neither the ROM nor
# N64Recomp.

[input]
entrypoint = 0x80000400
rom_file_path = "quest64.hm.z64"
symbols_file_path = "Quest64Syms/hardmode_syms.toml"
output_func_path = "src/game/hardmode/recompiled"
functions_per_output_file = 100000

[patches]
# Every function of the game itself: they must exist so calls out of the
# payload resolve to the game's recompiled functions, but they are already
# emitted into RecompiledFuncs/ by us.rev0.toml.
ignored = [
EOF
for my $n (@names) {
    print $cfg "    \"$n\",\n";
}
# Ignored by us.rev0.toml as well, so they are missing from funcs.h.
print $cfg "    \"__osBlockSum\",\n    \"__osPfsReleasePages\",\n    \"__osPfsDeclearPage\",\n";
print $cfg "]\n";
print $cfg <<'EOF';

# gcc emits "teq" after a division to trap on a zero divisor; N64Recomp does
# not handle the instruction. Replaced with nop (the divisions are exp-table
# lookups and get_rand's modulus, neither of which is zero in practice).
[[patches.instruction]]
func = "hm_func_80414940"
vram = 0x80414EB0
value = 0x00000000

[[patches.instruction]]
func = "hm_func_8041A190"
vram = 0x8041A1D0
value = 0x00000000
EOF
close $cfg;

printf "wrote %d payload functions, %d ignored game functions\n", scalar @funcs, scalar @names;
