#ifndef __TRACKER_H__
#define __TRACKER_H__

#include <cstdint>
#include <string>
#include <vector>

// The tracker (Tracker tab, assets/tracker.rml): two overlay windows in the
// style of Ship of Harkinian's. The item tracker shows the six boss items,
// the Boss Souls that have arrived (only in a seed with Boss Souls) and the
// six wings; the check
// tracker lists every check by area, found ones lit and the rest greyed out,
// with the area Brian is in opened. Either window can be unlocked and
// dragged with the mouse, then locked in place.
//
// Where a check's state comes from: chests and spirits from their save flags,
// bosses from the "beaten" byte, monsters from the kill hook (kept per save,
// like the connector's item mark, since the game keeps no record of them), and
// in an Archipelago game also from what the server says is checked. Gift NPCs
// leave nothing behind in the save, so they are only tracked while connected.
namespace zelda64::tracker {
    enum class Kind : uint8_t { Chest, Giver, Monster, Boss, Spirit };

    struct CheckInfo {
        int64_t location;   // the Archipelago location id
        Kind kind;
        int area;           // index into area_names
        const char* label;
    };

    // tracker_data.cpp, generated by tools/tracker_data.pl.
    extern const std::vector<const char*> area_names;
    extern const int monsters_area;
    extern const std::vector<CheckInfo> checks;
    // Per room, [map][submap], into area_names: where an interior is filed
    // is decided by the door that leads into it, not by its building set.
    extern const std::vector<std::vector<int>> room_area;

    struct Options {
        // The whole tracker: off, no window shows and the Tracker tab hides
        // every other setting.
        bool enabled = true;
        bool item_tracker = false;
        bool check_tracker = false;
        // Locked: the windows stay put. Unlocked: drag a window by its
        // title to move it or its corner to resize it. Scrolling, opening
        // areas and typing in the note work either way.
        bool locked = true;
        bool hide_done_areas = false;
        // No outline on the windows, locked or not.
        bool hide_borders = false;
        // The windows lose their title bars ("Tracker", "Checks", "Notes"),
        // locked or not; unlocked, a window is dragged by its edge instead.
        bool hide_titles = false;
        // The item tracker's Wings section.
        bool show_wings = true;
        // The item tracker's Boss Souls section (only ever shown in a seed
        // with Boss Souls).
        bool show_souls = true;
        // Each window's background: 0 solid, 1 translucent, 2 clear. (One
        // "background" setting once covered all three; it is read as the
        // starting value for any of these a settings file does not have.)
        int item_background = 1;
        int check_background = 1;
        int notes_background = 1;
        // The Notes window: free text, saved in tracker_notes.txt. It takes
        // the mouse whenever it is shown, locked or not, so it can be clicked
        // into and written in; the keyboard only while the note has focus.
        bool notes = false;
        // Window positions as fractions of the window, top-left corner; the
        // notes' size in dp (resized from its corner).
        float item_x = 0.01f, item_y = 0.18f;
        float check_x = 0.78f, check_y = 0.12f;
        float notes_x = 0.01f, notes_y = 0.55f;
        float notes_w = 280.0f, notes_h = 180.0f;
        // The check list's height in dp, set from its corner; it scrolls within.
        float check_h = 420.0f;
    };
    // The notes' text, kept in tracker_notes.txt.
    std::string load_notes();
    void save_notes(const std::string& text);
    // Applied straight away; saved in tracker.json.
    const Options& options();
    void set_options(const Options& options);

    // Game thread.
    void on_frame(uint8_t* rdram);
    void monster_killed(int id);
    // Gift NPC i (Archipelago's giver order) has been talked to in this save,
    // check or not; kept per save like the kills, since the game keeps no
    // "given" state. Bit i of givers_talked().
    void giver_talked(int i);
    uint32_t givers_talked();
    // The Controller Pak hooks: kills are filed against the save's contents.
    void save_progress(const std::string& save_key);
    void load_progress(const std::string& save_key);

    // What the windows show, rebuilt by the game thread a few times a second.
    struct Snapshot {
        uint32_t version = 0;
        bool in_game = false;
        bool archipelago = false;
        std::vector<uint8_t> found;     // per check
        std::vector<uint8_t> present;   // per check: part of this game
        int item_counts[32] = {};       // bag counts for item ids 0-31
        int souls_mode = 0;             // archipelago::tracker_souls: 0 none, 1 seven, 2 eight
        uint32_t souls = 0;             // bit n (1-8): that boss's Soul has arrived
        int area = -1;                  // where Brian is, or -1
    };
    // Copies the latest snapshot if it is newer than `have`. UI thread.
    bool snapshot(Snapshot& out, uint32_t have);
}

#endif
