#!/usr/bin/perl
# Writes src/game/tracker_data.cpp: every check the tracker shows, grouped
# into areas, and which area each of the game's 36 maps belongs to.
#
#   perl tools/tracker_data.pl
#
# The checks come from the logic workbook's Locations sheet (name, id, group,
# game area), the same rows the apworld is generated from, so the tracker and
# the Archipelago locations cannot disagree. The workbook's game areas are
# fine-grained ("Dondoran Castle King's Room"); the rules below fold them into
# the areas the tracker lists, in story order. Map names come from
# src/game/map_table.cpp.
use strict;
use warnings;
use File::Basename qw(dirname);

use lib dirname(__FILE__);
use Quest64Logic;

my $root = dirname(__FILE__) . '/..';

# Tracker areas in the order they are listed, each with the prefixes of the
# workbook game areas (and map names) that belong to it. The first match
# wins, so the longer prefixes come first.
my @areas = (
    [ 'Melrode',          'Monastery', 'Melrode' ],
    [ 'Holy Plains',      'Holy Plains' ],
    [ 'Connor Forest',    'Connor Forest' ],
    [ 'Dondoran Flats',   'Dondoran Flats' ],
    [ 'Dondoran',         'Dondoran' ],
    [ 'Glencoe Forest',   'Glencoe' ],
    [ 'West Carmaugh',    'West Carmagh', 'Greenoch' ],
    [ 'Larapool',         'Larapool' ],
    [ 'Cull Hazard',      'Cull Hazard' ],
    [ 'Normoon',          'Normoon' ],
    [ 'Windward Forest',  'Windward' ],
    [ 'Limelin',          'Limelin', 'West Limelin' ],
    [ 'Blue Cave',        'Blue Cave', "Nepty's arena" ],
    [ 'Isle of Skye',     'Isle of Skye' ],
    [ 'Baragoon Tunnel',  'Baragoon Tunnel' ],
    [ 'Dindom Dries',     'Dindom' ],
    [ 'Boil Hole',        'Boil Hole' ],
    [ 'Shamwood',         'Shamwood' ],
    [ 'Baragoon Moor',    'Baragoon Moor', 'Brannoch / Baragoon' ],
    [ 'Brannoch Castle',  'Brannoch' ],
    [ "Mammon's World",   "Mammon's World" ],
    [ 'Hidden Rooms',     'Hidden rooms' ],
    [ 'Monsters' ],   # every monster check, wherever it is met
);
my $monsters_area = $#areas;

sub area_of {
    my $place = shift;
    for my $i (0 .. $#areas) {
        my ($name, @prefixes) = @{ $areas[$i] };
        for my $p (@prefixes) {
            return $i if index($place, $p) == 0;
        }
    }
    return -1;
}

sub c_str { my $s = shift; $s =~ s/\\/\\\\/g; $s =~ s/"/\\"/g; return "\"$s\"" }

# ---------------------------------------------------------------- checks
my %kind_of = ('Chest' => 'Chest', 'Gift NPC' => 'Giver', 'Monster' => 'Monster', 'Boss' => 'Boss', 'Spirit' => 'Spirit');
my %prefix_of = (Chest => 'Chest - ', Giver => 'Giver - ', Monster => 'Defeat - ', Boss => 'Boss - ', Spirit => 'Spirit - ');
my %label_of = (Chest => 'Chest', Giver => 'Gift', Monster => '', Boss => 'Boss', Spirit => 'Spirit');

my $book = Quest64Logic::read_workbook("$root/DOCS/archipelago_logic.xlsx");
my $rows = $book->{Locations} or die "no Locations sheet\n";
my @checks;
for my $r (4 .. $#$rows) {
    my $name = Quest64Logic::cell($rows, $r, 1);
    next if $name eq '';
    my ($id, $group, $place) = (Quest64Logic::cell($rows, $r, 2), Quest64Logic::cell($rows, $r, 3), Quest64Logic::cell($rows, $r, 4));
    my $kind = $kind_of{$group} // die "Locations row $r: unknown group \"$group\"\n";
    my $area = $kind eq 'Monster' ? $monsters_area : area_of($place);
    die "Locations row $r: no tracker area for \"$place\"\n" if $area < 0;
    (my $label = $name) =~ s/^\Q$prefix_of{$kind}\E//;
    $label = "$label_of{$kind}: $label" if $label_of{$kind} ne '';
    push @checks, { id => hex($id), kind => $kind, area => $area, label => $label };
}
die "expected 277 checks, found " . scalar(@checks) . "\n" unless @checks == 277;

# ---------------------------------------------------------------- maps
my @map_area;
{
    open my $f, '<', "$root/src/game/map_table.cpp" or die "map_table.cpp: $!";
    while (<$f>) {
        next unless /^\s+"([^"]+)",\s+\/\/ (\d+)/;
        my $a = area_of($1);
        die "map $2 \"$1\": no tracker area\n" if $a < 0;
        $map_area[$2] = $a;
    }
    close $f;
    die "expected 36 maps, found " . scalar(@map_area) . "\n" unless @map_area == 36;
}

# ---------------------------------------------------------------- write
my $out = "// GENERATED by tools/tracker_data.pl from DOCS/archipelago_logic.xlsx and\n"
        . "// src/game/map_table.cpp; do not edit.\n"
        . "#include \"tracker.h\"\n\n"
        . "namespace zelda64::tracker {\n\n"
        . "const std::vector<const char*> area_names = {\n"
        . join('', map { "    " . c_str($_->[0]) . ",\n" } @areas)
        . "};\n\n"
        . "const int monsters_area = $monsters_area;\n\n"
        . "const std::vector<CheckInfo> checks = {\n";
for my $c (@checks) {
    $out .= sprintf("    { 0x%08X, Kind::%s, %d, %s },\n", $c->{id}, $c->{kind}, $c->{area}, c_str($c->{label}));
}
$out .= "};\n\n"
      . "const std::vector<int> map_area = { " . join(', ', @map_area) . " };\n\n"
      . "}\n";

my $path = "$root/src/game/tracker_data.cpp";
open my $o, '>', $path or die "$path: $!";
print $o $out;
close $o;
printf "wrote %s: %d checks in %d areas\n", $path, scalar(@checks), scalar(@areas);
